[package]
edition = "2021"
name    = "square-and-circle"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand = { workspace = true }
[lints]
workspace = true
