edition                  = "2021"
reorder_imports          = true
use_field_init_shorthand = true
use_small_heuristics     = "Max"
use_try_shorthand        = true

# let's wait mythical rustfmt 2.0
#unstable_features   = true
#group_imports       = "StdExternalCrate"
#imports_granularity = "Crate"
