[package]
edition = "2021"
name    = "number-system"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
[lints]
workspace = true
