[package]
name = "splitting-into-terms"
version = "0.1.0"
edition = "2021"

[dependencies]

[lints]
workspace = true
[package]
name = "splitting-into-terms"
version = "0.1.0"
edition = "2021"

[dependencies]

[lints]
workspace = true
